# Site settings
title: Trademapper
description: > # this means to ignore newlines until "baseurl:"
  Trademapper is an awesome way of visualising trade from, to, between different countries.
baseurl: "trademapper-js" # the subpath of your site, e.g. /blog/
url: "http://trademapper.github.io/" # the base hostname & protocol for your site
github_username:  trademapper

# Build settings
markdown: kramdown

# Permalink settings
permalink:     '/blog/:year/:title/'
paginate_path: '/blog/page:num/'

# Adding pages, which will be more useful here
include: ['_pages']
relative_permalinks: false
